### ISSUE TITLE
Delay in bot responses for #.

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/SamagraX-community#4]
What I observed while testing workflow with WhatsApp bot is, every time when I add # to go to the previous step, it takes 4 minutes to get an update response

_Originally posted by @Nik720 in https://github.com/Samagra-Development/SamagraX-community/discussions/3#discussioncomment-528433_

**Comment by aayushkedia95** [comment]
@nik720, Can you provide more information (formID) and the step at which you pressed # along with the XLSX of the form on that issue. That would enable us to reproduce it.

**Comment by Nik720** [comment]
@ChakshuGautam @aayushkedia95  sorry for late, here are the scenario 

**FormID**: SamagraX_AK_Test
**Input steps**: Hi AKBot => 1 => # (at any step it will reproduce)

<img width="300" alt="Screenshot 2021-03-26 at 12 53 58 PM" src="https://user-images.githubusercontent.com/33539271/112597184-cd5f0e80-8e32-11eb-8c1c-3fea4de44e7c.png">



**FormID**: digital_content_workflow_without_group_01
**Input steps**: Hi Tara => 1 => # (at any step it will reproduce)
**XLSX**: https://docs.google.com/spreadsheets/d/1PTEFJoAhRsvlvoZSbNiFQoB6-Yqxl6l4/edit#gid=1148196142

<img width="300" alt="Screenshot 2021-03-26 at 12 59 37 PM" src="https://user-images.githubusercontent.com/33539271/112597619-59713600-8e33-11eb-92f9-f5921fcbbf8d.png">

CC @vinukumar-vs @vrayulu

**Comment by ChakshuGautam** [comment]
Thanks for the screenshots. I am seeing the same behavior as well. I think this is due to the last pushed code as we have not seen this behavior before.

**Comment by Nik720** [comment]
Can you please also check that some of the HTML tags are not working in the WhatApp bot?  

<img width="300" alt="Screenshot 2021-03-26 at 1 51 10 PM" src="https://user-images.githubusercontent.com/33539271/112603154-9ab91400-8e3a-11eb-820a-5ca2395fba85.png">

**Comment by ChakshuGautam** [comment]
Hi @Nik720, xMessages inherently supports a subset of styling mentioned [here](https://samagra-development.github.io/docs/docs/XMessageSpec/#3-styling). So anything in the transformer (ODK in this case) should be formatted either through this or we could have a transformer that does this conversion post the ODK transformer (and HTML tags transformer).

**Comment by ChakshuGautam** [comment]
@Nik720 This is closed now. Please test.
